services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

  django:
    image: geek-django-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/apps
      
volumes:
  postgres-data:
