# Generated by Django 5.0.4 on 2024-07-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_liked"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Liked",
            new_name="Like",
        ),
    ]
